In [1]:
!cd ./Desktop/Projects/Ensemble-Indoor-Loc/

In [23]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, f1_score, confusion_matrix, roc_curve, roc_auc_score, classification_report
from sklearn.preprocessing import label_binarize
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder , normalize
from sklearn.model_selection import ShuffleSplit
from itertools import cycle

import seaborn as sns

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.model_selection import cross_val_score

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

from sklearn.ensemble import VotingClassifier

from matplotlib import pyplot

# Metric Functions


In [5]:

# Make the confusion matrix
def confusion_plot(y_test,y_pred,title):
    cmt = confusion_matrix(y_test,y_pred)
    plt.rcParams['figure.figsize'] = (10,8)
    sns.heatmap(cmt,fmt='',annot=True,linewidth=0.01,cmap=sns.cubehelix_palette(as_cmap=True))
    plt.title("confusion matrix {}".format(title))
    plt.xlabel("predicted")
    plt.ylabel("true")
    plt.show()


# generate classification report
def generate_classification_report(y_test,y_pred):
    report=pd.DataFrame.from_dict(classification_report(y_pred,y_test,output_dict=True)).T
    # report['Label']=[data_classes[i]  if i<5 else " " for i,x in enumerate(report.index)]
    report=report[['f1-score','precision','recall','support']]
    pd.set_option('display.max_rows', report.shape[0]+1)
    return report

# ROC Curve
def plot_roc_curve(y_test,proba,pos_label):
    fpr, tpr, thresholds = roc_curve(y_test, proba[:,pos_label], pos_label= pos_label)
    roc_auc = roc_auc_score(y_test, proba, multi_class='ovr')

    plt.rcParams['figure.figsize'] = (5,4)
    plt.plot(fpr, tpr,'k:',lw=5, label='average ROC curve (area = {0:0.2f})'.format(roc_auc))
    plt.plot([0 ,1],[0 ,1],'r')
    plt.legend(loc="lower right")
    # plt.title('ROC Curve for calss {0}'.format(data_classes[pos_label]))
    plt.ylabel('True Positive Rate')
    plt.xlabel('False Positive Rate')
    plt.show()


# ROC Curve for all classes
def plot_roc_curve_all(y_test,proba,n_class,title):
    for i in range(n_class):
      fpr, tpr, thresholds = roc_curve(y_test, proba[:,i],pos_label= i)
      plt.plot(fpr, tpr,lw=1)
    plt.plot([0 ,1],[0 ,1],'r')
    plt.title('ROC Curve for all classes in {}'.format(title))
    plt.ylabel('True Positive Rate')
    plt.xlabel('False Positive Rate')
    # plt.legend(data_classes)
    plt.show()

#Dateset Proccesses

In [6]:
data_train = pd.read_csv("C:\\Users\Hamid\content\JUIndoorLoc-Training-data.csv")
data_train.head(5)
data_test = pd.read_csv("C:\\Users\Hamid\content\JUIndoorLoc-Test-data.csv")
data_test.head(5)

<>:1: SyntaxWarning: invalid escape sequence '\H'
<>:3: SyntaxWarning: invalid escape sequence '\H'
<>:1: SyntaxWarning: invalid escape sequence '\H'
<>:3: SyntaxWarning: invalid escape sequence '\H'
C:\Users\Hamid\AppData\Local\Temp\ipykernel_2888\2129459651.py:1: SyntaxWarning: invalid escape sequence '\H'
  data_train = pd.read_csv("C:\\Users\Hamid\content\JUIndoorLoc-Training-data.csv")
C:\Users\Hamid\AppData\Local\Temp\ipykernel_2888\2129459651.py:3: SyntaxWarning: invalid escape sequence '\H'
  data_test = pd.read_csv("C:\\Users\Hamid\content\JUIndoorLoc-Test-data.csv")


Cid  AP001  AP002  AP003  AP004  AP005  AP006  AP007  AP008  AP009  \
0  L4-33-13    -77    -58    -66    -64    -92    -66    -66    -93    -93   
1  L4-33-13    -90    -58    -78    -56    -92    -74    -74    -87    -93   
2  L4-33-13    -80    -64    -78    -56    -92    -74    -74    -87    -93   
3  L4-33-13    -72    -60    -74    -58    -93    -75    -76    -95    -93   
4  L4-33-13    -82    -56    -74    -56    -93    -71    -76    -89   -110   

   ...  AP167  AP168  AP169  AP170  AP171  AP172  Rs  Hpr  Did             Ts  
0  ...   -110   -110   -110   -110   -110   -110   0    0   D2  1489813137748  
1  ...   -110   -110   -110   -110   -110   -110   0    0   D2  1489813179138  
2  ...   -110   -110   -110   -110   -110   -110   0    0   D2  1489812948443  
3  ...   -110   -110   -110   -110   -110   -110   0    0   D2  1489812959103  
4  ...   -110   -110   -110   -110   -110   -110   0    0   D2  1489813079167  

[5 rows x 177 columns]

In [7]:
frames = [data_train, data_test]
mergedDataset = pd.concat(frames)
mergedDataset.head(5)

Cid  AP001  AP002  AP003  AP004  AP005  AP006  AP007  AP008  AP009  \
0  L4-40-1    -84    -80    -71    -58   -110    -72    -71   -110   -110   
1  L4-40-1    -84    -79    -71    -58   -110    -72    -71   -110   -110   
2  L4-40-1   -110   -110    -70    -56   -110    -69    -68   -110   -110   
3  L4-40-1   -110   -110    -70    -53   -110    -69    -68   -110   -110   
4  L4-37-2    -84    -82    -75    -65   -110    -73    -75   -110   -110   

   ...  AP167  AP168  AP169  AP170  AP171  AP172  Rs  Hpr  Did             Ts  
0  ...   -110   -110   -110   -110   -110   -110   0    1   D4  1469870570949  
1  ...   -110   -110   -110   -110   -110   -110   0    1   D4  1470047205646  
2  ...   -110   -110   -110   -110   -110   -110   0    1   D4  1469870932338  
3  ...   -110   -110   -110   -110   -110   -110   0    1   D4  1470047629440  
4  ...   -110   -110   -110   -110   -110   -110   0    1   D4  1469876622694  

[5 rows x 177 columns]

In [8]:
mergedDataset['Did'] = mergedDataset['Did'].astype(str).str[1]
mergedDataset['Did'] = pd.to_numeric(mergedDataset['Did'])

In [9]:
#make X_train from Tr
X = mergedDataset.loc[:, (mergedDataset.columns != 'Ts') & (mergedDataset.columns != 'Cid')]
y = mergedDataset.Cid



le = LabelEncoder()
le.fit(y)
le.transform(y)


X_train = X
y_train_encode =  le.transform(y)


In [10]:
print(len(np.unique(y_train_encode)))
print(len(y.unique()))

991
991


# KNN With Shuffle

In [11]:
knn_model = KNeighborsClassifier(n_neighbors=5,n_jobs = -1)
cv = ShuffleSplit(n_splits=5, test_size=0.15, random_state=42)
scores = cross_val_score(knn_model, X_train, y_train_encode, cv=cv)

In [12]:
scores

array([0.79211564, 0.78528252, 0.78107753, 0.7892247 , 0.77713535])

# Logestic Regression

In [14]:
logestic_regression = LogisticRegression(random_state=1,n_jobs = -1)
cv = ShuffleSplit(n_splits=5, test_size=0.15, random_state=42)
scores = cross_val_score(logestic_regression, X_train, y_train_encode, cv=cv)

In [15]:
scores

array([0.40236531, 0.42286465, 0.41997372, 0.42785808, 0.4260184 ])

# Gaussian Naive Bayse

In [16]:
gaussian_nb = GaussianNB()
scores = cross_val_score(gaussian_nb, X_train, y_train_encode, cv=cv)

In [17]:
scores

array([0.43390276, 0.41576873, 0.42417871, 0.42812089, 0.43574244])

# Random Forest

In [20]:
n_estimators = 100
rf_model = RandomForestClassifier(n_estimators=n_estimators, max_depth=None,
                                      min_samples_split=2, random_state=42)
scores = cross_val_score(rf_model, X_train, y_train_encode, cv=cv)

In [21]:
scores

array([0.96688568, 0.97082786, 0.97240473, 0.97503285, 0.96714849])

# Hard Voting

In [24]:
hard_voting = VotingClassifier(
     estimators=[('lr', logestic_regression), ('rf', rf_model), ('gnb', gaussian_nb),('knn', knn_model)],
     voting='hard')
scores = cross_val_score(hard_voting, X_train, y_train_encode, cv=cv)

In [25]:
scores

array([0.8412615 , 0.83942181, 0.84809461, 0.84678055, 0.85151117])

# Weighted Average Probabilities (Soft Voting)

In [26]:
soft_voting= VotingClassifier(
     estimators=[('lr', logestic_regression), ('rf', rf_model), ('gnb', gaussian_nb),('knn', knn_model)],
     voting='soft',
     weights=[1, 2, 1, 2])
scores = cross_val_score(hard_voting, X_train, y_train_encode, cv=cv)

In [27]:
scores

array([0.8412615 , 0.83942181, 0.84809461, 0.84678055, 0.85151117])

In [28]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std()))

Accuracy: 0.85 (+/- 0.00)
